// vibe-watcher.js
// Run with: node vibe-watcher.js

import fs from 'fs';
import path from 'path';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import chokidar from 'chokidar';

const PORT = 3000;
const WS_PORT = 3001;
const ROLLBACK_LOG = 'VIBE_ROLLBACK.md';
const WATCH_EXTENSIONS = ['.html', '.css', '.js', '.jsx', '.ts', '.tsx', '.json'];

// Create rollback log if it doesn't exist
function initRollbackLog() {
  if (!fs.existsSync(ROLLBACK_LOG)) {
    const header = `# 🎸 VIBE ROLLBACK LOG\n\n> Auto-generated by vibe-watcher.js | ${new Date().toLocaleString()}\n\n`;
    fs.writeFileSync(ROLLBACK_LOG, header);
  }
}

// Log a snapshot to rollback file
function logSnapshot(description = 'Auto-save', filesChanged = []) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const prettyTime = new Date().toLocaleString();
  
  const entry = `
## 📸 Snapshot: ${timestamp}

- **Time**: ${prettyTime}
- **Vibe**: ${description}
- **Files changed**: ${filesChanged.join(', ') || 'Unknown'}
- **Revert command**: \`git checkout <hash>\` or restore from backup

---
`;
  fs.appendFileSync(ROLLBACK_LOG, entry);
  console.log(`\x1b[36m📝 Logged: ${description}\x1b[0m`);
}

// Watch for file changes and trigger reload + logging
function watchFiles() {
  const watcher = chokidar.watch('.', {
    ignored: /(node_modules|\.git|vibe-watcher\.js|VIBE_ROLLBACK\.md)/,
    persistent: true,
    ignoreInitial: true
  });

  let debounceTimer;
  
  watcher.on('change', (filePath) => {
    const ext = path.extname(filePath).toLowerCase();
    if (WATCH_EXTENSIONS.includes(ext)) {
      console.log(`\x1b[33m🔄 Changed: ${filePath}\x1b[0m`);
      
      // Debounce logging (avoid 100 logs for 1 save)
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        logSnapshot(`Editing ${path.basename(filePath)}`, [filePath]);
        notifyClients(filePath);
      }, 500);
    }
  });
  
  console.log('\x1b[32m👁️ Watching for file changes...\x1b[0m');
  return watcher;
}

// WebSocket server for live reload
let clients = [];
function setupWebSocket() {
  const wss = new WebSocketServer({ port: WS_PORT });
  
  wss.on('connection', (ws) => {
    clients.push(ws);
    console.log(`\x1b[32m🔌 Browser connected (${clients.length} total)\x1b[0m`);
    
    ws.on('close', () => {
      clients = clients.filter(client => client !== ws);
    });
  });
  
  console.log(`\x1b[32m🔌 WebSocket server running on port ${WS_PORT}\x1b[0m`);
}

function notifyClients(changedFile) {
  const message = JSON.stringify({ type: 'reload', file: changedFile });
  clients.forEach(client => {
    if (client.readyState === 1) { // WebSocket.OPEN
      client.send(message);
    }
  });
  console.log(`\x1b[33m📡 Notified ${clients.length} browser(s) to reload\x1b[0m`);
}

// HTTP server to serve files and inject live reload script
function serveFiles() {
  const server = createServer((req, res) => {
    let filePath = req.url === '/' ? '/index.html' : req.url;
    filePath = path.join(process.cwd(), filePath);
    
    const ext = path.extname(filePath);
    const contentType = {
      '.html': 'text/html',
      '.css': 'text/css',
      '.js': 'application/javascript',
      '.json': 'application/json',
    }[ext] || 'text/plain';
    
    fs.readFile(filePath, (err, content) => {
      if (err) {
        res.writeHead(404);
        res.end('File not found — vibe on, but carefully');
        return;
      }
      
      // Inject WebSocket reload script into HTML files
      if (ext === '.html') {
        const injectScript = `
          <script>
            (function() {
              const ws = new WebSocket('ws://localhost:${WS_PORT}');
              ws.onmessage = (event) => {
                const data = JSON.parse(event.data);
                if (data.type === 'reload') {
                  console.log('🎸 Vibe reloading...', data.file);
                  location.reload();
                }
              };
              ws.onopen = () => console.log('🎸 Vibe watcher connected — auto-reload active');
              console.log('🎸 Vibe mode: ON — every save = instant refresh + rollback log');
            })();
          </script>
        </body>
        `;
        
        let html = content.toString();
        html = html.replace('</body>', injectScript);
        
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(html);
      } else {
        res.writeHead(200, { 'Content-Type': contentType });
        res.end(content);
      }
    });
  });
  
  server.listen(PORT, () => {
    console.log(`\x1b[35m`);
    console.log('🎸🎸🎸 VIBE WATCHER ACTIVE 🎸🎸🎸');
    console.log(`\x1b[0m`);
    console.log(`   🌐 http://localhost:${PORT}`);
    console.log(`   📝 Rollback log: ${ROLLBACK_LOG}`);
    console.log(`   🔄 Auto-refresh on save`);
    console.log(`   💾 Snapshots logged every time you save`);
    console.log(`\x1b[90m   Press Ctrl+C to stop\x1b[0m\n`);
  });
}

// Optional: Manual snapshot via keyboard
function setupManualSnapshot() {
  process.stdin.setRawMode(true);
  process.stdin.resume();
  process.stdin.on('data', (key) => {
    if (key.toString() === 's') {
      logSnapshot('MANUAL SNAPSHOT — you triggered this via "s" key', ['manual']);
      console.log('\x1b[32m💾 Manual snapshot saved! Press "s" again anytime\x1b[0m');
    }
    if (key.toString() === '\u0003') { // Ctrl+C
      console.log('\n\x1b[31m👋 Vibe session ended. Keep creating.\x1b[0m');
      process.exit();
    }
  });
  console.log('\x1b[90m💡 Press "s" anytime to save a manual snapshot to the rollback log\x1b[0m\n');
}

// Run everything
async function main() {
  initRollbackLog();
  setupWebSocket();
  serveFiles();
  watchFiles();
  setupManualSnapshot();
}

main().catch(console.error);